export const SET_DIALOG_OPEN = 'SET_DIALOG_OPEN';
export const SET_MESSAGE_OPEN = 'SET_MESSAGE_OPEN';

export const EARLY_ACCESS_START = 'EARLY_ACCESS_START';
export const EARLY_ACCESS_SUCCESS = 'EARLY_ACCESS_SUCCESS';
export const EARLY_ACCESS_FAIL = 'EARLY_ACCESS_FAIL';
