export const FETCH_FOLLOW_START = 'FETCH_FOLLOW_START';
export const FETCH_FOLLOW_SUCCESS = 'FETCH_FOLLOW_SUCCESS';
export const FETCH_FOLLOW_FAIL = 'FETCH_FOLLOW_FAIL';

export const FOLLOW_START = 'FOLLOW_START';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAIL = 'FOLLOW_FAIL';

export const UN_FOLLOW_START = 'UN_FOLLOW_START';
export const UN_FOLLOW_SUCCESS = 'UN_FOLLOW_SUCCESS';
export const UN_FOLLOW_FAIL = 'UN_FOLLOW_FAIL';

export const SET_SPAC_EMAIL_ALERT_START = 'SPAC_EMAIL_ALERT_START';
export const SET_SPAC_EMAIL_ALERT_SUCCESS = 'SPAC_EMAIL_ALERT_SUCCESS';
export const SET_SPAC_EMAIL_ALERT_FAIL = 'SPAC_EMAIL_ALERT_FAIL';

export const SET_SPAC_SMS_ALERT_START = 'SPAC_SMS_ALERT_START';
export const SET_SPAC_SMS_ALERT_SUCCESS = 'SET_SPAC_SMS_ALERT_SUCCESS';
export const SET_SPAC_SMS_ALERT_FAIL = 'SET_SPAC_SMS_ALERT_FAIL';
