export const FETCH_TOP_LIST_START = 'FETCH_TOP_LIST_START';
export const FETCH_TOP_LIST_SUCCESS = 'FETCH_TOP_LIST_SUCCESS';
export const FETCH_TOP_LIST_FAIL = 'FETCH_TOP_LIST_FAIL';

export const FETCH_SPAC_LIST_START = 'FETCH_SPAC_LIST_START';
export const FETCH_SPAC_LIST_SUCCESS = 'FETCH_SPAC_LIST_SUCCESS';
export const FETCH_SPAC_LIST_FAIL = 'FETCH_SPAC_LIST_FAIL';

export const FETCH_SPAC_HISTORICAL_START = 'FETCH_SPAC_HISTORICAL_START';
export const FETCH_SPAC_HISTORICAL_SUCCESS = 'FETCH_SPAC_HISTORICAL_SUCCESS';
export const FETCH_SPAC_HISTORICAL_FAIL = 'FETCH_SPAC_HISTORICAL_FAIL';
