export const SET_SMS_SEND = 'SET_SMS_SEND';
export const SET_EMAIL_SEND = 'SET_EMAIL_SEND';

export const PROFILE_SAVE_START = 'PROFILE_SAVE_START';
export const PROFILE_SAVE_SUCCESS = 'PROFILE_SAVE_SUCCESS';
export const PROFILE_SAVE_FAIL = 'PROFILE_SAVE_FAIL';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const SEND_STRIPE_PAYMENT_EMAIL = 'SEND_STRIPE_PAYMENT_EMAIL';

export const SUBSCRIBE_USER_START = 'SUBSCRIBE_USER_START';
export const SUBSCRIBE_USER_SUCCESS = 'SUBSCRIBE_USER_SUCCESS';
export const SUBSCRIBE_USER_FAIL = 'SUBSCRIBE_USER_FAIL';

export const UN_SUBSCRIBE_START = 'UN_SUBSCRIBE_START';
export const UN_SUBSCRIBE_SUCCESS = 'UN_SUBSCRIBE_SUCCESS';
export const UN_SUBSCRIBE_FAIL = 'UN_SUBSCRIBE_FAIL';
