export const FETCH_TOP_QUERY_START = 'FETCH_TOP_QUERY_START';
export const FETCH_TOP_QUERY_SUCCESS = 'FETCH_TOP_QUERY_SUCCESS';
export const FETCH_TOP_QUERY_FAIL = 'FETCH_TOP_QUERY_FAIL';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';

export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
