export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const SEND_EMAIL_START = 'SEND_EMAIL_START';
export const SEND_SMS_START = 'SEND_SMS_START';
